language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - pip install codecov

install:
  - pip install -r tests-requirements.txt

script: py.test --cov=pendulum tests/

after_success:
  - codecov
